---
- set_fact:
    _mco_exists: True

# Check whether the MachineConfigPool resource type exists at all on this cluster
- name: Check if MachineConfigPool resource type exists
  shell: |
    oc api-resources --api-group=machineconfiguration.openshift.io --no-headers | grep -q MachineConfigPool
  failed_when: false
  register: _mcp_api

- set_fact:
    _mco_exists: False
  when: _mcp_api.rc != 0

# Check if the MachineConfigPool worker exists. Sometimes after provisioning of a cluster this may take a few minutes
- name: Check if MachineConfigPool worker exists
  shell: |
    oc get mcp worker
  failed_when: false
  register: _mcp_worker
  until: _mcp_worker.rc==0
  delay: 10
  retries: 30
  when:
  - _mco_exists
  - _existing_ocp_infra_type != 'ibm-roks'

# Check if the MachineConfigPool worker exists for existing OpenShift
- name: Check if MachineConfigPool worker exists (final check)
  shell: |
    oc get mcp worker
  failed_when: false
  register: _mcp_worker
  when: _mco_exists

- set_fact:
    _mco_exists: False
  when:
  - _mco_exists
  - _mcp_worker.rc != 0

- include_role:
    name: run-command
  vars:
    _p_command_description: Pause the MachineConfig operator to disable rebooting of compute nodes
    _p_command: oc patch --type=merge --patch='{"spec":{"paused":true}}' machineconfigpool/worker
  when: 
  - _mco_exists
  - _existing_ocp_infra_type != 'aws-rosa'

- include_tasks: non-mco-prepare-node-settings.yml
  when: 
  - not _mco_exists
  - not cpd_dry_run